version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: vehiculosdb

  microservicio:
    image: microservicio-vehiculos
    container_name: microservicio-vehiculos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017  # Este reemplaza tu localhost
    restart: on-failure

volumes:
  mongo_data:
