# The version line will generate a warning but can be kept for local compatibility
# version: '3.8' .. or 3.9 is recommended for local development

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: vehiculosdb

  microservicio:
    # For GitHub Actions, we need to use the published image
    image: juanpotes0922/microserviciogolang:latest
    container_name: microservicio-vehiculos
    # Remove the build section as we're using the pre-built image
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017
    restart: on-failure

volumes:
  mongo_data: