name: Deploy and Test Microservicio

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build, Scan and Push Docker Image for Microservicio Golang"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull juanpotes0922/microserviciogolang:latest

      - name: Run container from image
        run: |
          docker run -d --name microserviciogolang -p 8080:8080 juanpotes0922/microserviciogolang:latest

      - name: Wait for container to be ready
        run: sleep 5

      - name: Test Hello World endpoint
        run: |
          RESPONSE=$(curl -s http://localhost:8080)
          echo "Response: $RESPONSE"
          if [[ "$RESPONSE" != *"Hola Mundo"* ]]; then
            echo "❌ No se recibió 'Hola Mundo'"
            exit 1
          fi
          echo "✅ Se recibió 'Hola Mundo'"
