name: Deploy and Test Microservicio

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build, Scan and Push Docker Image for Microservicio Golang"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for containers to be ready
        run: sleep 10

      - name: Test Hello World endpoint
        run: |
          RESPONSE=$(curl -s http://localhost:8080)
          echo "Response: $RESPONSE"
          if [[ "$RESPONSE" != *"Hola Mundo"* ]]; then
            echo "❌ No se recibió 'Hola Mundo'"
            exit 1
          fi
          echo "✅ Se recibió 'Hola Mundo'"
